/* 48 seleções da Copa 2026 — bandeira + nome + confederação */
window.TEAMS = [
  {f:"🇺🇸",n:"Estados Unidos",c:"CONCACAF"},
  {f:"🇨🇦",n:"Canadá",c:"CONCACAF"},
  {f:"🇲🇽",n:"México",c:"CONCACAF"},
  {f:"🇨🇷",n:"Costa Rica",c:"CONCACAF"},
  {f:"🇵🇦",n:"Panamá",c:"CONCACAF"},
  {f:"🇯🇲",n:"Jamaica",c:"CONCACAF"},
  {f:"🇧🇷",n:"Brasil",c:"CONMEBOL"},
  {f:"🇦🇷",n:"Argentina",c:"CONMEBOL"},
  {f:"🇺🇾",n:"Uruguai",c:"CONMEBOL"},
  {f:"🇨🇴",n:"Colômbia",c:"CONMEBOL"},
  {f:"🇪🇨",n:"Equador",c:"CONMEBOL"},
  {f:"🇵🇾",n:"Paraguai",c:"CONMEBOL"},
  {f:"🇵🇪",n:"Peru",c:"CONMEBOL"},
  {f:"🇪🇸",n:"Espanha",c:"UEFA"},
  {f:"🇫🇷",n:"França",c:"UEFA"},
  {f:"🏴󠁧󠁢󠁥󠁮󠁧󠁿",n:"Inglaterra",c:"UEFA"},
  {f:"🇵🇹",n:"Portugal",c:"UEFA"},
  {f:"🇩🇪",n:"Alemanha",c:"UEFA"},
  {f:"🇮🇹",n:"Itália",c:"UEFA"},
  {f:"🇳🇱",n:"Holanda",c:"UEFA"},
  {f:"🇧🇪",n:"Bélgica",c:"UEFA"},
  {f:"🇭🇷",n:"Croácia",c:"UEFA"},
  {f:"🇩🇰",n:"Dinamarca",c:"UEFA"},
  {f:"🇨🇭",n:"Suíça",c:"UEFA"},
  {f:"🇦🇹",n:"Áustria",c:"UEFA"},
  {f:"🇵🇱",n:"Polônia",c:"UEFA"},
  {f:"🇷🇸",n:"Sérvia",c:"UEFA"},
  {f:"🇹🇷",n:"Turquia",c:"UEFA"},
  {f:"🇳🇴",n:"Noruega",c:"UEFA"},
  {f:"🏴󠁧󠁢󠁷󠁬󠁳󠁿",n:"País de Gales",c:"UEFA"},
  {f:"🇲🇦",n:"Marrocos",c:"CAF"},
  {f:"🇸🇳",n:"Senegal",c:"CAF"},
  {f:"🇳🇬",n:"Nigéria",c:"CAF"},
  {f:"🇪🇬",n:"Egito",c:"CAF"},
  {f:"🇬🇭",n:"Gana",c:"CAF"},
  {f:"🇨🇲",n:"Camarões",c:"CAF"},
  {f:"🇩🇿",n:"Argélia",c:"CAF"},
  {f:"🇨🇮",n:"Costa do Marfim",c:"CAF"},
  {f:"🇹🇳",n:"Tunísia",c:"CAF"},
  {f:"🇯🇵",n:"Japão",c:"AFC"},
  {f:"🇰🇷",n:"Coreia do Sul",c:"AFC"},
  {f:"🇮🇷",n:"Irã",c:"AFC"},
  {f:"🇦🇺",n:"Austrália",c:"AFC"},
  {f:"🇸🇦",n:"Arábia Saudita",c:"AFC"},
  {f:"🇶🇦",n:"Catar",c:"AFC"},
  {f:"🇮🇶",n:"Iraque",c:"AFC"},
  {f:"🇺🇿",n:"Uzbequistão",c:"AFC"},
  {f:"🇳🇿",n:"Nova Zelândia",c:"OFC"}
];

/* sugestões de prato por país (fallback se o jogador não digitar) */
window.DISH_HINT = {
  "Brasil":"Feijoada","Argentina":"Asado","Itália":"Lasanha","Japão":"Ramen",
  "México":"Tacos al Pastor","Espanha":"Paella","França":"Ratatouille",
  "Portugal":"Bacalhau à Brás","Marrocos":"Tagine","Coreia do Sul":"Bibimbap",
  "Tailândia":"Pad Thai","Alemanha":"Bratwurst","Estados Unidos":"Cheeseburger"
};

/* ============================================================
   FEED SOCIAL — pratos das OUTRAS duplas da sala
   curtidas, comentários e avaliações em estrelas
   ============================================================ */
window.SOCIAL_FEED = [
  {id:"s1",flag:"🇮🇹",country:"Itália",duo:"DUDA & LARA",emoji:"🍝",time:"há 12 min",
    caption:"Lasanha à bolonhesa que a nonna aprovaria 🤌 3 camadas de molho!",
    likes:42,liked:false,
    reviews:[{who:"BIA",s:5,t:"Massa no ponto, parabéns!"},{who:"JOÃO",s:4,t:"Faltou um cadinho de molho 😅"}]},
  {id:"s2",flag:"🇯🇵",country:"Japão",duo:"PEDRO & VINI",emoji:"🍜",time:"há 38 min",
    caption:"Tonkotsu caseiro, caldo cozinhou 6 horas. Vale cada minuto.",
    likes:67,liked:false,
    reviews:[{who:"LARA",s:5,t:"Caldo absurdo de bom"},{who:"MEL",s:5,t:"Quero delivery disso JÁ"}]},
  {id:"s3",flag:"🇲🇽",country:"México",duo:"CAIO & MEL",emoji:"🌮",time:"há 1 h",
    caption:"Tacos al pastor com abacaxi grelhado 🔥 nível restaurante",
    likes:55,liked:true,
    reviews:[{who:"DUDA",s:4,t:"Apimentado na medida"},{who:"VINI",s:5,t:"Me passa a receita!"},{who:"BIA",s:4,t:"Top demais"}]},
  {id:"s4",flag:"🇮🇳",country:"Índia",duo:"NINA & TOM",emoji:"🍛",time:"há 2 h",
    caption:"Butter chicken + naan feito na chapa. A casa toda cheirando a curry.",
    likes:38,liked:false,
    reviews:[{who:"PEDRO",s:4,t:"Cremoso demais, amei"}]},
  {id:"s5",flag:"🇫🇷",country:"França",duo:"GABI & RUI",emoji:"🥖",time:"há 3 h",
    caption:"Ratatouille montado pétala por pétala. Deu trabalho mas ó 😍",
    likes:73,liked:false,
    reviews:[{who:"MEL",s:5,t:"Mais bonito que o do filme"},{who:"CAIO",s:5,t:"Obra de arte"},{who:"NINA",s:4,t:"Lindo!"}]},
  {id:"s6",flag:"🇰🇷",country:"Coreia do Sul",duo:"YARA & ZÉ",emoji:"🍲",time:"há 5 h",
    caption:"Bibimbap coloridão com ovo perfeito. Gochujang caseiro!",
    likes:29,liked:false,
    reviews:[{who:"RUI",s:4,t:"Equilíbrio perfeito de sabores"}]},
  {id:"s7",flag:"🇵🇹",country:"Portugal",duo:"FLÁ & IGOR",emoji:"🐟",time:"há 8 h",
    caption:"Bacalhau à Brás cremoso, batata palha na hora. Saudade de Lisboa.",
    likes:21,liked:false,
    reviews:[{who:"GABI",s:4,t:"Clássico bem executado"}]},
  {id:"s8",flag:"🇲🇦",country:"Marrocos",duo:"SOFIA & KAI",emoji:"🍢",time:"há 11 h",
    caption:"Tagine de cordeiro com damasco. Cozinhou lento, desmancha na boca.",
    likes:34,liked:false,
    reviews:[{who:"ZÉ",s:5,t:"Tempero impecável"},{who:"YARA",s:4,t:"Que aroma!"}]}
];
